CREATE DATABASE COLABORADOR
GO
USE COLABORADOR
GO
CREATE TABLE T_COLABORADOR(
COD_COLABORADOR INT PRIMARY KEY,
DNI_COLABORADOR VARCHAR(50) UNIQUE,
NOM_COLABORADOR VARCHAR(50),
FEC_NACIMIENTO SMALLDATETIME,
FEC_INGRESO SMALLDATETIME,
CAR_COLABORADOR VARCHAR(50),
ESTADO VARCHAR(50) default 'Activo')

select * from T_COLABORADOR

---

IF NOT EXISTS(select * from sys.databases where name = 'MIRENIEC')
BEGIN
	create database MIRENIEC	
END

GO

USE MIRENIEC

GO

IF NOT EXISTS(SELECT * FROM SYSOBJECTS WHERE name = 'PERSONA')
BEGIN

CREATE TABLE PERSONA(
	ID INT IDENTITY(1,1) NOT NULL,
	DNI VARCHAR(50) NOT NULL UNIQUE,
	NOMBRES VARCHAR(200) NOT NULL,
	APELLIDO_PATERNO VARCHAR(200) NOT NULL,
	APELLIDO_MATERNO VARCHAR(200) NOT NULL,
	FECHA_NACIMIENTO SMALLDATETIME NOT NULL,
	ESTADO CHAR(1) NOT NULL DEFAULT 'A'
 )
	
END

GO

IF NOT EXISTS(SELECT * FROM PERSONA WHERE DNI = '41203195')
BEGIN
	INSERT INTO PERSONA(DNI,NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_NACIMIENTO,ESTADO) 
	VALUES('41203195','ROGER EDUARD','PAUCAR','NAVARRO','1991-18-09 02:30:00','A')
END

GO

IF NOT EXISTS(SELECT * FROM PERSONA WHERE DNI = '41721537')
BEGIN
	INSERT INTO PERSONA(DNI,NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_NACIMIENTO,ESTADO) 
	VALUES('41721537','KARLA','ALVARADO','SALAZAR','1992-11-11 10:10:00','A')
END

IF NOT EXISTS(SELECT * FROM PERSONA WHERE DNI = '44444444')
BEGIN
	INSERT INTO PERSONA(DNI,NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_NACIMIENTO,ESTADO) 
	VALUES('44444444','JOSE','PEREZ','SOLIS','1991-18-09 02:30:00','I')
END

GO

IF EXISTS(SELECT * FROM SYSOBJECTS WHERE name = 'MIRENIEC_GETPERSONA')
BEGIN
	DROP PROC MIRENIEC_GETPERSONA
END

GO

CREATE PROCEDURE OBTENER_PERSONA
@DNI VARCHAR (50)
AS
BEGIN
SELECT NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,FECHA_NACIMIENTO FROM PERSONA WHERE DNI=@DNI
END

GO

USE MASTER
GO

CREATE LOGIN Usuario_AsignacionPC 
    WITH PASSWORD = '340$Uuxwp7Mcxo7Khy';
GO

USE MIRENIEC
GO

CREATE USER Usuario_AsignacionPC FOR LOGIN Usuario_AsignacionPC;
GO

GRANT SELECT ON PERSONA TO Usuario_AsignacionPC
GRANT EXECUTE ON OBTENER_PERSONA TO Usuario_AsignacionPC

-- select * from persona

--CREATE PROCEDURE MIRENIEC_GETPERSONA  
--@DNI VARCHAR(50)  
--AS  
--BEGIN  
   
-- IF EXISTS(SELECT DNI FROM DBO.PERSONA WHERE DNI = @DNI)  
--  BEGIN  
  
--  declare @identity INT
  
--  IF ((SELECT MAX(Persona_Id) FROM Veterinaria.dbo.Cliente) = 0)
--  BEGIN
--	set @identity = 1
--  END
--  ELSE
--  BEGIN
--	set @identity = (SELECT MAX(Persona_Id) + 1 FROM Veterinaria.dbo.Cliente)
--  END
  
  
--   SELECT '1' + ';' + UPPER(NOMBRES)+ ';' + UPPER(APELLIDO_PATERNO) + ';' +   
--   UPPER(APELLIDO_MATERNO) + ';' + DNI + ';' + CAST(@identity AS VARCHAR(10))
--   FROM PERSONA WHERE DNI = @DNI  
     
--  END  
-- ELSE  
--  BEGIN  
--   SELECT '0; ; ; ; ; '  
--  END  
  
--END

--GO

--EXEC MIRENIEC_GETPERSONA '41203195'

--GO

--EXEC MIRENIEC_GETPERSONA '41203195ERERE'

