CREATE DATABASE COLABORADOR
GO
USE COLABORADOR
GO
CREATE TABLE T_COLABORADOR(
COD_COLABORADOR INT PRIMARY KEY,
NOM_COLABORADOR VARCHAR(50),
FEC_NACIMIENTO SMALLDATETIME,
FEC_INGRESO SMALLDATETIME,
CAR_COLABORADOR VARCHAR(50),
ESTADO VARCHAR(50) default 'Activo')



select * from T_COLABORADOR

